Train:
  batch_size: 128
  learning_rate: 0.001
  reg: 0.001
  epochs: 1000
  steps: [6, 8]
  warmup: 0
  momentum: 0.9
  seed: 42
  patience: 50
  min_delta: 0.00001

data:
  save_best: True
  save_preds: True
  save_loss: True

network:
  model: CNN-LSTM # CNN or CNN-LSTM
  optimizer: ADAM # base or ADAM
  scheduler: True
  class_weighting: False
  early_stopping: False
  context: True
  body_only: False
